class MachineModel {
  final dynamic plant;
  final dynamic fac;
  final dynamic area;
  final dynamic macId;
  final dynamic pic;

  MachineModel({this.plant, this.fac, this.area, this.macId, this.pic});

  factory MachineModel.fromJson(Map<String, dynamic> json) => MachineModel(
    plant: json['plant'],
    fac: json['fac'],
    area: json['area'],
    pic: json['pic'],
    macId: json['macId'],
  );
}

final List<MachineModel> mocckMachines = [
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-002"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-005"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-006"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-007"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-008"),
  MachineModel(plant: "612K", fac: "Fac C", area: "CORE PIN", macId: "A-009"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-011"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-012"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-015"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "CUTTING 2-1",
    macId: "A-017",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-019"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-020"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-021"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-023"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-024"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-025"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-026"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-027"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-028"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-039"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-043"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-044"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-045"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-046"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-047"),
  MachineModel(plant: "612K", fac: "Fac C", area: "TAPER PIN", macId: "A-054"),
  MachineModel(plant: "612K", fac: "Fac C", area: "SPRUE BUSH", macId: "A-055"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-057"),
  MachineModel(plant: "612K", fac: "Fac C", area: "OILLESS", macId: "A-061"),
  MachineModel(plant: "612K", fac: "Fac C", area: "CAM", macId: "A-062"),
  MachineModel(plant: "612K", fac: "Fac C", area: "OILLESS", macId: "A-063"),
  MachineModel(plant: "612K", fac: "Fac C", area: "CAM", macId: "A-064"),
  MachineModel(plant: "612K", fac: "Fac C", area: "CAM", macId: "A-066"),
  MachineModel(plant: "612K", fac: "Fac C", area: "OILLESS", macId: "A-070"),
  MachineModel(plant: "612K", fac: "Fac C", area: "TAPER PIN", macId: "A-072"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-074"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-077"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-081"),
  MachineModel(plant: "612K", fac: "Fac C", area: "OILLESS", macId: "A-083"),
  MachineModel(plant: "612K", fac: "Fac A", area: "MC", macId: "A-1000"),
  MachineModel(plant: "612K", fac: "Fac A", area: "MC", macId: "A-1001"),
  MachineModel(plant: "612K", fac: "Fac C", area: "OILLESS", macId: "A-1005"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-102"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1039"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "SPRUE BUSH",
    macId: "A-1040",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-1044",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-1045",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-1046",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-1047",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-1048",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1056"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-1065"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-1066"),
  MachineModel(plant: "612K", fac: "Fac C", area: "CAM", macId: "A-1067"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1068"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-1069",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1070"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-1071",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-1073",
  ),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1084"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1139"),
  MachineModel(plant: "612K", fac: "Fac C", area: "CAM", macId: "A-1143"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1146"),
  MachineModel(plant: "612K", fac: "Fac A", area: "MC", macId: "A-1153"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-1154",
  ),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-1168"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-1169",
  ),
  MachineModel(plant: "612K", fac: "Fac B", area: "MC", macId: "A-1170"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1174"),
  MachineModel(plant: "612K", fac: "Fac C", area: "OILLESS", macId: "A-1175"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1208"),
  MachineModel(plant: "612K", fac: "Fac C", area: "HEAT", macId: "A-1211"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1225"),
  MachineModel(plant: "612K", fac: "Fac C", area: "TAPER PIN", macId: "A-1275"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "MAGNET LOCK",
    macId: "A-1283",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "MAGNET LOCK",
    macId: "A-1284",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1288"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1293"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1306"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1307"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1308"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1309"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1310"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1311"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1334"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1335"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1336"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1368"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1369"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1370"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1371"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-1389"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1390"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1391"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1392"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1393"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1397"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1400"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1401"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1402"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-1412"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-1413"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-1414"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1420"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1421"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1422"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1423"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1424"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1425"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-1426"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-1427"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1428"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-1429"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1436"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1437"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1438"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1439"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1440"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1442"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1443"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1451"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1453"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1454"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1455"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "SPRUE BUSH",
    macId: "A-1456",
  ),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1457"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1458"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1459"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1460"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1461"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1469"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1470"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1471"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-1473A"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-1473B"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-1474A"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-1474B"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1475"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1477"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1478"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1479"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-1482"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1483"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1484"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1485"),
  MachineModel(plant: "612K", fac: "Fac C", area: "OILLESS", macId: "A-1486"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1487"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1488"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1489"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-1494",
  ),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-1498"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-1499"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1508"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-1510"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-1511"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1517"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1518"),
  MachineModel(plant: "612K", fac: "Fac A", area: "MC", macId: "A-1519"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-1520"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1521"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1522"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1523"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-1531"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-1532"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1534"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1535"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-1536"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1537"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-1557"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1559"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-1562"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1563"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1564"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-1569"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-1570"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-1571",
  ),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-1572"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1575"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "ROLLER LOCK",
    macId: "A-1576",
  ),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1578"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1579"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1580"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1581"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-1587"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1589"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-1592"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1593"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1594"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1595"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-1596"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1597"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-1598",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-1612"),
  MachineModel(plant: "612K", fac: "Fac C", area: "HEAT", macId: "A-1613"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1617"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-1619"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1620"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-1625"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1626"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1627"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1628"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1629"),
  MachineModel(plant: "612K", fac: "Fac C", area: "CORE PIN", macId: "A-1630"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1634"),
  MachineModel(plant: "612K", fac: "Fac A", area: "MC", macId: "A-1635"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-1636"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-1637"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1638"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-1639"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1640"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-1644"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-1645"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1647"),
  MachineModel(plant: "612K", fac: "Fac A", area: "MC", macId: "A-1648"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1649"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-165"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Drill", macId: "A-1650"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1651"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-1652"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-166"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-1668",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-1669",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-1670",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-1671",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-1671B",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-1672",
  ),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1676"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1677"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1678"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-1679"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-1680"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1700"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1728"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-1729"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-1747"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-1883"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-1884"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-1915",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-1916",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "SPRUE BUSH",
    macId: "A-1917",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-1918",
  ),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1919"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-1920"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-1929"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-1943"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1959"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-1960"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-1972"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-1999"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2000"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-2001"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-2002"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-2003",
  ),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2004"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2012"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-2017",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-2018",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-2019",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-2020",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-2021",
  ),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2025"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-2031",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "SPRUE BUSH",
    macId: "A-2032",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "SPRUE BUSH",
    macId: "A-2033",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2046"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-2051"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-2052"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2053"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2075"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2081"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-2082"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-2088"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-2089"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2090"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2091"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2092"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2093"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-2094"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2095"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2096"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2097"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2098"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2099"),
  MachineModel(plant: "612K", fac: "Fac C", area: "CORE PIN", macId: "A-2103"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2108"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2115"),
  MachineModel(plant: "612K", fac: "Fac A", area: "MC", macId: "A-2119"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2137"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2138"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2139"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Drill", macId: "A-2143"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-2144"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2147"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2148"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-2149"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Others", macId: "A-2150"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2151"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2152"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2153"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2155"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-2156",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-2157",
  ),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2158"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2159"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2160"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2161"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2163"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2167"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-2170"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2171"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-2172"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2176"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2177"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2178"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2179"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "SPRUE BUSH",
    macId: "A-2182",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-2183"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2184"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2185"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Others", macId: "A-2203"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2204"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2205"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2211"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2218"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2219"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-2220"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2222"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Drill", macId: "A-2223"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2228"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-2230"),
  MachineModel(plant: "612K", fac: "Fac C", area: "TAPER PIN", macId: "A-2231"),
  MachineModel(plant: "612K", fac: "Fac C", area: "OILLESS", macId: "A-2239"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2240"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Others", macId: "A-2242"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2243"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-2251"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-2252"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-2253"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-2259",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "ROLLER LOCK",
    macId: "A-2260",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-2274",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "MC", macId: "A-2287"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2291"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-2292"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2310"),
  MachineModel(plant: "612K", fac: "Fac A", area: "MC", macId: "A-2331"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2347"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2348"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2349"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2350"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2351"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2352"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2371"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2372"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2373"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-2374"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2375"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2376"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2381"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2388"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2391"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2392"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2393"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2394"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Others", macId: "A-2395"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2396"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2397"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2399"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-2400"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-2401"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-2402"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-2402-1"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2408"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2414"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2415"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-2430",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "A-2431",
  ),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2432"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "SPRUE BUSH",
    macId: "A-2435",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-2436",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-2437",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2438"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2446"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2449"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2450"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2451"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2452"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2453"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2454"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2455"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2456"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2460"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2461"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2462"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Others", macId: "A-2465"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2466"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-2473",
  ),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2476"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2477"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2478"),
  MachineModel(plant: "612K", fac: "Fac C", area: "HEAT", macId: "A-2488"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2491"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2492"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Others", macId: "A-2545"),
  MachineModel(plant: "612K", fac: "Fac C", area: "HEAT", macId: "A-2548"),
  MachineModel(plant: "612K", fac: "Fac C", area: "HEAT", macId: "A-2556"),
  MachineModel(plant: "612K", fac: "Fac C", area: "HEAT", macId: "A-2557"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2565"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2566"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2591"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2592"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-2605"),
  MachineModel(plant: "612K", fac: "Fac C", area: "HEAT", macId: "A-2609"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2621"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2622"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "CUTTING 2-1",
    macId: "A-2623",
  ),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2624"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2628"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2629"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2630"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2632"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2633"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2644"),
  MachineModel(plant: "612K", fac: "Fac A", area: "MC", macId: "A-2645"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2656"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Others", macId: "A-2668"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2669"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-2670"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2676"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2677"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2678"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-2679"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-268"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2681"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2682"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2683"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2684"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2685"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2686"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2687"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2692"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2693"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-2696"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-2697"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2703"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2704"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2705"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2706"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2707"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2708"),
  MachineModel(plant: "612K", fac: "Fac C", area: "HEAT", macId: "A-2709"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2716"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-2719"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2721"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2728"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2729"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "SPRUE BUSH",
    macId: "A-2730",
  ),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2739"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-2742"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2743"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2746"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Others", macId: "A-2751"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Others", macId: "A-2752"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Others", macId: "A-2753"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "SPRUE BUSH",
    macId: "A-2755",
  ),
  MachineModel(plant: "612K", fac: "Fac B", area: "Heat", macId: "A-2757"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-2769"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-277"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-2770"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MA", macId: "A-2776"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-330"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-330A1"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-330D1"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-330D2"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-339A"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-339B"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-340"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-362"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-386",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-417"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-418"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-421"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-423",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-435"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-436"),
  MachineModel(plant: "612K", fac: "Fac C", area: "CORE PIN", macId: "A-437"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-438"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-440"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-441"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-442"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-445"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-446"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-447"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-448"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-449"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-452"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-453"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-455"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-457"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-458"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-459"),
  MachineModel(plant: "612K", fac: "Fac C", area: "TAPER PIN", macId: "A-472"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-473"),
  MachineModel(plant: "612K", fac: "Fac C", area: "CORE PIN", macId: "A-474"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-475"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-476"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-482"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-490"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-491"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-495"),
  MachineModel(plant: "612K", fac: "Fac C", area: "SPRUE BUSH", macId: "A-497"),
  MachineModel(plant: "612K", fac: "Fac C", area: "CAM", macId: "A-498"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-513"),
  MachineModel(plant: "612K", fac: "Fac A", area: "MC", macId: "A-523"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-525"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-526"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-546"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-551"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-552"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-560"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-561"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-565"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-582"),
  MachineModel(plant: "612K", fac: "Fac C", area: "SPRUE BUSH", macId: "A-629"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Rough", macId: "A-630"),
  MachineModel(plant: "612K", fac: "Fac C", area: "OILLESS", macId: "A-631"),
  MachineModel(plant: "612K", fac: "Fac C", area: "SPRUE BUSH", macId: "A-632"),
  MachineModel(plant: "612K", fac: "Fac C", area: "SPRUE BUSH", macId: "A-633"),
  MachineModel(plant: "612K", fac: "Fac C", area: "SPRUE BUSH", macId: "A-634"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "CUTTING 2-1",
    macId: "A-635",
  ),
  MachineModel(plant: "612K", fac: "Fac C", area: "SPRUE BUSH", macId: "A-636"),
  MachineModel(plant: "612K", fac: "Fac C", area: "SPRUE BUSH", macId: "A-637"),
  MachineModel(plant: "612K", fac: "Fac C", area: "SPRUE BUSH", macId: "A-638"),
  MachineModel(plant: "612K", fac: "Fac C", area: "SPRUE BUSH", macId: "A-639"),
  MachineModel(plant: "612K", fac: "Fac C", area: "SPRUE BUSH", macId: "A-640"),
  MachineModel(plant: "612K", fac: "Fac C", area: "SPRUE BUSH", macId: "A-641"),
  MachineModel(plant: "612K", fac: "Fac C", area: "SPRUE BUSH", macId: "A-642"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-643"),
  MachineModel(plant: "612K", fac: "Fac C", area: "SPRUE BUSH", macId: "A-644"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-662"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-669"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-670"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-676"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-693"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-694"),
  MachineModel(plant: "612K", fac: "Fac C", area: "TAPER PIN", macId: "A-713"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-714"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-715"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-723"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-734",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-735",
  ),
  MachineModel(plant: "612K", fac: "Fac C", area: "CAM", macId: "A-736"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-747"),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-749"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-750"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-751"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-752"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-754"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-755"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-756"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-757"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-758"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-759"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-760"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-761"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-763",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-764",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-765",
  ),
  MachineModel(plant: "612K", fac: "Fac C", area: "MOLD MTO", macId: "A-766"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-767",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-768",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-769",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-770"),
  MachineModel(plant: "612K", fac: "Fac A", area: "MC", macId: "A-771"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-774",
  ),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-797"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-810"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-811",
  ),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-868"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-870"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "CUTTING 2-1",
    macId: "A-872",
  ),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "A-873"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-881"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-882"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-883"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-884"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-885"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-886"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Others", macId: "A-900"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-916"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-917"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "A-926"),
  MachineModel(plant: "612K", fac: "Fac C", area: "TAPER PIN", macId: "A-932"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-936"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-937"),
  MachineModel(plant: "612K", fac: "Fac C", area: "TAPER PIN", macId: "A-938"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "A-949"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-968"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-969"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-970"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "A-971",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "ROLLER LOCK",
    macId: "A-972",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "ROLLER LOCK",
    macId: "A-973",
  ),
  MachineModel(plant: "612K", fac: "Fac B", area: "Fine", macId: "A-974"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "ROLLER LOCK",
    macId: "A-975",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "A-976"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-998"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-999"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "A-999 R"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "D-1012"),
  MachineModel(plant: "612K", fac: "Fac C", area: "TAPER PIN", macId: "D-1013"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "CUTTING 2-1",
    macId: "D-1032",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Others", macId: "D-1033"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "D-1035"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "D-1037",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "D-1041"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "D-2038"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "EP-01",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "EP-02",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "EP-03",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "EP-04",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "EP-05",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "EP-06",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "EJECTOR PIN",
    macId: "EP-07",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "L-030"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "L-070"),
  MachineModel(plant: "612K", fac: "Fac C", area: "TAPER PIN", macId: "L-072"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "L-090"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "L-092"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "L-094"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "L-140"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Heat", macId: "L-147"),
  MachineModel(plant: "612K", fac: "Fac C", area: "TAPER PIN", macId: "L-151"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "L-154"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "TAPER BLOCK",
    macId: "L-160",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "L-161"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "L-180"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "L-192",
  ),
  MachineModel(plant: "612K", fac: "Fac C", area: "TAPER PIN", macId: "L-206"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "L-225"),
  MachineModel(plant: "612K", fac: "Fac C", area: "OILLESS", macId: "L-239"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "L-242",
  ),
  MachineModel(plant: "612K", fac: "Fac C", area: "CAM", macId: "L-248"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "L-258"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "L-289"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "L-290"),
  MachineModel(plant: "612K", fac: "Fac C", area: "SPRUE BUSH", macId: "L-299"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "L-315"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "L-317"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "L-337"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "L-339"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "L-347"),
  MachineModel(plant: "612K", fac: "Fac C", area: "TAPER PIN", macId: "L-348"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "L-349"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "L-350"),
  MachineModel(plant: "612K", fac: "Fac A", area: "MC", macId: "L-368"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "L-382",
  ),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "L-383",
  ),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "L-394"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "L-407"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "L-408"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "L-412"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "L-416"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-016"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-018"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-019"),
  MachineModel(plant: "612K", fac: "Fac C", area: "OILLESS", macId: "M-026"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-103"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-104"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-108"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-109"),
  MachineModel(plant: "612K", fac: "Fac C", area: "RETAINER", macId: "M-111"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "M-119"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "M-120"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-126"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-127"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-129"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-130"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-131"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-132"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-135"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-136"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-144"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-145"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-146"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-147"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-148"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Fine", macId: "M-151"),
  MachineModel(plant: "612K", fac: "Others", area: "Others", macId: "M-152"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "M-153"),
  MachineModel(plant: "612K", fac: "Fac A", area: "Rough", macId: "N-7"),
  MachineModel(plant: "612K", fac: "Fac B", area: "Others", macId: "A-2803"),
  MachineModel(
    plant: "612K",
    fac: "Fac C",
    area: "PARTING LOCK",
    macId: "A-2794",
  ),
  MachineModel(plant: "612K", fac: "Fac A", area: "Drill", macId: "A-2831"),
  MachineModel(plant: "612K", fac: "Fac C", area: "TAPER PIN", macId: "A-893"),
  MachineModel(
    plant: "612K",
    fac: "Outside",
    area: "Fac A",
    macId: "Water pump",
  ),
  MachineModel(plant: "612K", fac: "Outside", area: "Fac A", macId: "Garage"),
  MachineModel(
    plant: "612K",
    fac: "Outside",
    area: "Fac A",
    macId: "WH Material",
  ),
  MachineModel(
    plant: "612K",
    fac: "Outside",
    area: "Fac A",
    macId: "Nitrogen gas",
  ),
  MachineModel(
    plant: "612K",
    fac: "Outside",
    area: "Fac A",
    macId: "Garbage house",
  ),
  MachineModel(plant: "612K", fac: "Outside", area: "Fac A", macId: "Oil tank"),
  MachineModel(plant: "612K", fac: "Outside", area: "Fac A", macId: "Others"),
  MachineModel(
    plant: "612K",
    fac: "Outside",
    area: "Fac B",
    macId: "Water pump",
  ),
  MachineModel(plant: "612K", fac: "Outside", area: "Fac B", macId: "Garage"),
  MachineModel(
    plant: "612K",
    fac: "Outside",
    area: "Fac B",
    macId: "WH Material",
  ),
  MachineModel(
    plant: "612K",
    fac: "Outside",
    area: "Fac B",
    macId: "Nitrogen gas",
  ),
  MachineModel(
    plant: "612K",
    fac: "Outside",
    area: "Fac B",
    macId: "Garbage house",
  ),
  MachineModel(plant: "612K", fac: "Outside", area: "Fac B", macId: "Oil tank"),
  MachineModel(plant: "612K", fac: "Outside", area: "Fac B", macId: "Others"),
  MachineModel(
    plant: "612K",
    fac: "Outside",
    area: "Fac C",
    macId: "Water pump",
  ),
  MachineModel(plant: "612K", fac: "Outside", area: "Fac C", macId: "Garage"),
  MachineModel(
    plant: "612K",
    fac: "Outside",
    area: "Fac C",
    macId: "WH Material",
  ),
  MachineModel(
    plant: "612K",
    fac: "Outside",
    area: "Fac C",
    macId: "Nitrogen gas",
  ),
  MachineModel(
    plant: "612K",
    fac: "Outside",
    area: "Fac C",
    macId: "Garbage house",
  ),
  MachineModel(plant: "612K", fac: "Outside", area: "Fac C", macId: "Oil tank"),
  MachineModel(plant: "612K", fac: "Outside", area: "Fac C", macId: "Others"),
];
